stages:          # List of stages for jobs, and their order of execution
  - testRUNNER
  - build
  - test
  - lint
  - drawio
  - deploy

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - echo "Compiling the code..."
    - echo "Compile complete."

unit-test-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  script:
    - echo "Running unit tests... This will take about 60 seconds."
    - echo "Code coverage is 90%"

eslint:
  stage: lint
  image: node
  script:
    # Install eslint
    - npm install eslint
    - yarn add typescript
    - yarn add --dev @gitlab/eslint-plugin @typescript-eslint/eslint-plugin @typescript-eslint/parser eslint-plugin-jsx-a11y
    # Run eslint
    - node_modules/eslint/bin/eslint.js ./client/
    - node_modules/eslint/bin/eslint.js ./server/


drawio:on-schedule:
  stage: drawio
  image: "docker-registry.univ-nantes.fr/bousse-e/docker-drawio"
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
  script:
    - mkdir -p documentation/client/out
    - drawio --export -f png --crop --output documentation/client/out documentation/client/
    - ls documentation/client/out
    - git checkout main
    - git pull
    - git add documentation/client/out/*
    - git config user.name "CI Runner DrawIO"
    - git config user.email "ci_runner@nothing.org"
    - git commit -m "[skip ci] DrawIO rendering"
    - git push https://cirunner:${HTTP_GIT_TOKEN}@gitlab.com/grenoble-inp-ensimag/4MMCAW6/G2/ProjetACOLWEB/ProjetACOLWEB_bruno_carrere_damien_gieules_dorian_voland_guilherme_faccin_huth_samuel_thiken.git 
    

deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  environment: production
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
