### GET token
POST http://{{baseUrl}}/user/login HTTP/1.1
content-type: application/json

{
    "username": "carrereb"
}

### GET token
GET http://{{baseUrl}}/getjwtDeleg/Bruno HTTP/1.1

### GET whoami
GET http://{{baseUrl}}/whoami HTTP/1.1
x-access-token: {{token}}

### GET users
GET http://{{baseUrl}}/api/users/ HTTP/1.1
x-access-token: {{token}}

### POST user
POST http://{{baseUrl}}/api/users/ HTTP/1.1
content-type: application/json

{
    "username": "Bruno"
}
