@baseUrl = 127.0.0.1:3000
@contentType = application/json
# @name login1
POST http://{{baseUrl}}/user/register/ HTTP/1.1
content-type: {{contentType}}

{
    "username": "p1",
    "password": "AZERTY1234"
}
###
@token1 = {{login1.response.body.token}}
# @name login2
POST http://{{baseUrl}}/user/register/ HTTP/1.1
content-type: application/json

{
    "username": "p2",
    "password": "AZERTY1234"
}
###
@token2 = {{login2.response.body.token}}


### POST new game
POST http://{{baseUrl}}/game/new HTTP/1.1
x-access-token: {{token1}}
Content-Type: {{contentType}}

{
    "nbPlayerMin": 5,
    "nbPlayerMax": 20,
    "dayLength": 2000,
    "nightLength": 2000,
    "startDate": 1681915913629,
    "percentageWerewolf": 0.33,
    "probaContamination": 0.1,
    "probaInsomnie": 0.1,
    "probaVoyance": 0.1,
    "probaSpiritisme": 0.1
}

### join game1
POST http://{{baseUrl}}/game/1/join HTTP/1.1
x-access-token: {{token2}}

### check update
GET http://{{baseUrl}}/game/1/details/ HTTP/1.1
x-access-token: {{token1}}